"""crear_tabla_game_items

Revision ID: 5522a5b33732
Revises: 81392139acb8
Create Date: 2026-06-25 20:07:04.072059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5522a5b33732'
down_revision: Union[str, Sequence[str], None] = '81392139acb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icon_path', sa.String(length=255), nullable=False),
    sa.Column('visual_asset_path', sa.String(length=255), nullable=True),
    sa.Column('audio_asset_path', sa.String(length=255), nullable=True),
    sa.Column('stack_maximo', sa.Integer(), nullable=False),
    sa.Column('precio_compra', sa.Integer(), nullable=False),
    sa.Column('precio_venta', sa.Integer(), nullable=False),
    sa.Column('propiedades', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_items_categoria'), 'game_items', ['categoria'], unique=False)
    op.create_index(op.f('ix_game_items_id'), 'game_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_items_id'), table_name='game_items')
    op.drop_index(op.f('ix_game_items_categoria'), table_name='game_items')
    op.drop_table('game_items')
    # ### end Alembic commands ###
